# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ar_mailer_rails3}
  s.version = "2.1.8"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Yuanyi Zhang"]
  s.date = %q{2010-04-10}
  s.default_executable = %q{ar_sendmail_rails3}
  s.description = %q{ArMailer wrapper for Rails 3}
  s.email = %q{zhangyuanyi@gmail.com}
  s.executables = ["ar_sendmail_rails3"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
     "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "History.txt",
     "LICENSE.txt",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/ar_sendmail_rails3",
     "lib/ar_mailer_rails3.rb",
     "lib/ar_mailer_rails3/active_record.rb",
     "lib/ar_mailer_rails3/ar_sendmail.rb",
     "lib/generators/ar_mailer_rails3/ar_mailer_rails3_generator.rb",
     "lib/generators/ar_mailer_rails3/templates/ar_mailer.rb",
     "lib/generators/ar_mailer_rails3/templates/migration.rb",
     "lib/generators/ar_mailer_rails3/templates/model.rb",
     "lib/smtp_tls.rb",
     "test/test_armailer.rb",
     "test/test_arsendmail.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/yzhang/ar_mailer_rails3}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{ArMailer wrapper for Rails 3}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

